# Trace Analysis

Workflow:
1. **Scan** — load results, find failures, spot patterns
2. **Read** — pick a trace, read the conversation step by step
3. **Note** — write down what you observe (open coding)
4. **Cluster** — after 20-30 traces, group your notes into failure categories
5. **Fix** — change prompts/tools/behavior, rerun, compare

In [1]:
import json
from pathlib import Path

import pandas as pd

TRACES_DIR = Path("../traces")
pd.set_option("display.max_colwidth", 60)
pd.set_option("display.max_rows", 50)

## 1. Scan — find failures and patterns

In [2]:
results = pd.read_csv(TRACES_DIR / "results.csv")
results["passed"] = results["passed"].astype(bool)

print(f"{len(results)} results: {results['passed'].sum()} passed, {(~results['passed']).sum()} failed")

display_cols = ["workspace", "question", "passed", "tool_calls", "failed_assertions"]
if "category" in results.columns:
    display_cols.insert(1, "category")
results[display_cols].sort_values("passed")

28 results: 24 passed, 4 failed

,workspace,category,question,passed,tool_calls,failed_assertions
25,world-factbook,single_fact,What is the population of Japan?,False,0,"contains_any ['123,201,945', '123.2 million', '123 milli..."
22,sherlock-holmes,single_doc,"What happens in ""A Scandal in Bohemia""?",False,2,"contains_any ['photograph', 'king']"
8,sherlock-holmes,single_doc,"What happens in ""A Scandal in Bohemia""?",False,2,contains 'irene adler'
11,world-factbook,single_fact,What is the population of Japan?,False,0,"contains_any ['123,201,945', '123.2 million', '123 milli..."
0,federalist-papers,single_doc,What does Federalist No. 10 argue about factions?,True,3,NaN
24,sherlock-holmes,multi_doc,What methods does Holmes use across the stories?,True,8,NaN
23,sherlock-holmes,single_doc,How does Holmes solve the case in The Speckled Band?,True,7,NaN
21,origin-of-species,enumeration,What examples of variation under domestication does Darw...,True,11,NaN
20,origin-of-species,single_doc,How does Darwin explain the struggle for existence?,True,6,NaN
19,origin-of-species,single_doc,What does Darwin say about natural selection in Chapter 4?,True,3,NaN
18,federalist-papers,comparison,How do Hamilton and Madison differ on federal power?,True,11,NaN
17,federalist-papers,single_doc,What does Hamilton say about standing armies?,True,7,NaN
16,federalist-papers,multi_doc,What are the main themes across the Federalist Papers?,True,9,NaN
15,federalist-papers,enumeration,Which papers discuss the judiciary?,True,7,NaN
13,world-factbook,enumeration,Which countries in the dataset are in Africa?,True,3,NaN
26,world-factbook,comparison,Compare the economies of Brazil and Argentina.,True,7,NaN
12,world-factbook,comparison,Compare the economies of Brazil and Argentina.,True,8,NaN
10,sherlock-holmes,multi_doc,What methods does Holmes use across the stories?,True,8,NaN
9,sherlock-holmes,single_doc,How does Holmes solve the case in The Speckled Band?,True,3,NaN
7,origin-of-species,enumeration,What examples of variation under domestication does Darw...,True,7,NaN
6,origin-of-species,single_doc,How does Darwin explain the struggle for existence?,True,7,NaN
5,origin-of-species,single_doc,What does Darwin say about natural selection in Chapter 4?,True,7,NaN
4,federalist-papers,comparison,How do Hamilton and Madison differ on federal power?,True,17,NaN
3,federalist-papers,single_doc,What does Hamilton say about standing armies?,True,5,NaN
2,federalist-papers,multi_doc,What are the main themes across the Federalist Papers?,True,8,NaN
1,federalist-papers,enumeration,Which papers discuss the judiciary?,True,5,NaN
14,federalist-papers,single_doc,What does Federalist No. 10 argue about factions?,True,7,NaN
27,world-factbook,enumeration,Which countries in the dataset are in Africa?,True,12,NaN

In [3]:
# Pass rate by category (if available)
if "category" in results.columns:
    results.groupby("category")["passed"].agg(["sum", "count", "mean"]).rename(
        columns={"sum": "passed", "count": "total", "mean": "pass_rate"}
    ).sort_values("pass_rate")
else:
    print("No category column — rerun collect_traces.py to populate it")

In [4]:
# Pass rate by model
results.groupby("model")["passed"].agg(["sum", "count", "mean"]).rename(
    columns={"sum": "passed", "count": "total", "mean": "pass_rate"}
).sort_values("pass_rate")

                             passed  total  pass_rate
model
openrouter/qwen/qwen3-coder      24     28   0.857143

In [5]:
# Spot the two failure modes: 0 tools = skipped tools, 20 tools = hit max_turns
failures = results[~results["passed"]]
failures[["model", "workspace", "question", "tool_calls", "failed_assertions", "error"]]

,model,workspace,question,tool_calls,failed_assertions,error
8,openrouter/qwen/qwen3-coder,sherlock-holmes,"What happens in ""A Scandal in Bohemia""?",2,contains 'irene adler',NaN
11,openrouter/qwen/qwen3-coder,world-factbook,What is the population of Japan?,0,"contains_any ['123,201,945', '123.2 million', '123 milli...",NaN
22,openrouter/qwen/qwen3-coder,sherlock-holmes,"What happens in ""A Scandal in Bohemia""?",2,"contains_any ['photograph', 'king']",NaN
25,openrouter/qwen/qwen3-coder,world-factbook,What is the population of Japan?,0,"contains_any ['123,201,945', '123.2 million', '123 milli...",NaN

## 2. Read — pick a trace, step through the conversation

In [6]:
def load_trace(model_slug: str, workspace: str, question_slug: str) -> dict:
    path = TRACES_DIR / model_slug / workspace / f"{question_slug}.json"
    return json.loads(path.read_text())


def list_traces(model_slug: str) -> pd.DataFrame:
    """List all available trace files for a model."""
    rows = []
    model_dir = TRACES_DIR / model_slug
    for ws_dir in sorted(model_dir.iterdir()):
        if not ws_dir.is_dir():
            continue
        for trace_file in sorted(ws_dir.glob("*.json")):
            data = json.loads(trace_file.read_text())
            inner = data.get("trace", data)
            rows.append({
                "workspace": ws_dir.name,
                "slug": trace_file.stem,
                "passed": data["passed"],
                "tools": len(inner.get("tool_calls", [])),
                "question": data["question"][:60],
            })
    return pd.DataFrame(rows)


# List available models
print("Available models:")
for d in sorted(TRACES_DIR.iterdir()):
    if d.is_dir():
        print(f"  {d.name}")

Available models:
  openrouter-deepseek-deepseek-v3-2
  openrouter-qwen-qwen3-coder

In [7]:
# Pick a model and list its traces
MODEL = "openrouter-qwen-qwen3-coder"  # <-- change this
list_traces(MODEL)

,workspace,slug,passed,tools,question
0,federalist-papers,how-do-hamilton-and-madison-differ-on-federal-power,True,11,How do Hamilton and Madison differ on federal power?
1,federalist-papers,what-are-the-main-themes-across-the-federalist-papers,True,9,What are the main themes across the Federalist Papers?
2,federalist-papers,what-does-federalist-no-10-argue-about-factions,True,7,What does Federalist No. 10 argue about factions?
3,federalist-papers,what-does-hamilton-say-about-standing-armies,True,7,What does Hamilton say about standing armies?
4,federalist-papers,which-papers-discuss-the-judiciary,True,7,Which papers discuss the judiciary?
5,origin-of-species,how-does-darwin-explain-the-struggle-for-existence,True,6,How does Darwin explain the struggle for existence?
6,origin-of-species,what-does-darwin-say-about-natural-selection-in-chapter-4,True,3,What does Darwin say about natural selection in Chapter 4?
7,origin-of-species,what-examples-of-variation-under-domestication-does-darw...,True,11,What examples of variation under domestication does Darw...
8,sherlock-holmes,how-does-holmes-solve-the-case-in-the-speckled-band,True,7,How does Holmes solve the case in The Speckled Band?
9,sherlock-holmes,what-happens-in-a-scandal-in-bohemia,False,2,"What happens in ""A Scandal in Bohemia""?"
10,sherlock-holmes,what-methods-does-holmes-use-across-the-stories,True,8,What methods does Holmes use across the stories?
11,world-factbook,compare-the-economies-of-brazil-and-argentina,True,7,Compare the economies of Brazil and Argentina.
12,world-factbook,what-is-the-population-of-japan,False,0,What is the population of Japan?
13,world-factbook,which-countries-in-the-dataset-are-in-africa,True,12,Which countries in the dataset are in Africa?

In [ ]:
from html import escape
from IPython.display import HTML, display


def _format_json(text: str) -> str:
    """Pretty-print JSON, or return original text."""
    try:
        return json.dumps(json.loads(text), indent=2)
    except (json.JSONDecodeError, TypeError):
        return text


def _tool_result_summary(text: str) -> str:
    """One-line summary of a tool result."""
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return f"{len(text)} chars"
    if "error" in data:
        return f"error: {data['error']}"
    if "files" in data:
        names = [f["path"] for f in data["files"]]
        if len(names) <= 3:
            return f"{data.get('count', len(names))} files: {', '.join(names)}"
        return f"{data.get('count', len(names))} files"
    if "matches" in data:
        return f"{data.get('total_matches', len(data['matches']))} matches"
    if "content" in data:
        return f"{data.get('lines_returned', '?')} lines from {data.get('path', '?')}"
    if "stdout" in data:
        stdout = data["stdout"].strip()
        exit_code = data.get("exit_code", "?")
        if exit_code == 0:
            preview = stdout[:80] + "..." if len(stdout) > 80 else stdout
            return f"stdout ({len(stdout)} chars): {preview}" if stdout else "ok (no output)"
        return f"exit_code={exit_code}"
    if "result" in data:
        return f"result: {data['result']}"
    return f"{len(text)} chars"


def _sub_call_summary(sc: dict) -> str:
    """One-line summary of a sub_call entry."""
    name = sc.get("name", "?")
    args = sc.get("args", {})
    chars = sc.get("result_chars", 0)
    arg_parts = ", ".join(f"{k}={v!r}" for k, v in args.items())
    return f"{name}({arg_parts}) → {chars} chars"


def _collapsible(summary_html: str, detail_text: str, open_: bool = False) -> str:
    open_attr = " open" if open_ else ""
    return (
        f"<details{open_attr}><summary>{summary_html}</summary>"
        f"<pre style='margin:4px 0 8px 16px;font-size:12px;color:#555;'>{escape(detail_text)}</pre>"
        f"</details>"
    )


def _render_assertions(assertions: dict) -> str:
    lines = []
    for name, ok in assertions.items():
        icon = "✓" if ok else "✗"
        color = "#4a4" if ok else "#c44"
        lines.append(f"<span style='color:{color};'>{icon}</span> {escape(name)}")
    return "&nbsp;&nbsp;".join(lines)


def _tool_def_names(tools: list[dict]) -> list[str]:
    return [t.get("function", {}).get("name", "?") for t in tools]


def _render_tools(tools: list[dict]) -> str:
    """Collapsible block showing tool definitions sent with every API call."""
    if not tools:
        return ""
    names = _tool_def_names(tools)
    detail = json.dumps(tools, indent=2)
    return _collapsible(
        f"<span style='color:#888;font-size:13px;'>"
        f"{len(tools)} tool definitions: {', '.join(names)}</span>",
        detail,
    )


def _render_cached(messages: list[dict], tools: list[dict] | None = None) -> str:
    """Collapsible block summarizing cached (already-seen) context."""
    if not messages and not tools:
        return ""
    summary_parts = []
    if messages:
        summary_parts.append(f"{len(messages)} cached messages")
    if tools:
        summary_parts.append(f"{len(tools)} tool defs")
    summary = " + ".join(summary_parts)

    lines = []
    if tools:
        names = _tool_def_names(tools)
        lines.append(f"[tools] {', '.join(names)}")
    for m in messages:
        role = m["role"]
        content = m.get("content") or ""
        tool_calls = m.get("tool_calls", [])
        if role == "system":
            lines.append(f"[system] ({len(content)} chars)")
        elif role == "user":
            lines.append(f"[user] {content[:100]}")
        elif role == "assistant":
            if tool_calls:
                names = ", ".join(tc["function"]["name"] for tc in tool_calls)
                lines.append(f"[assistant] calls {names}")
            else:
                lines.append(f"[assistant] ({len(content)} chars)")
        elif role == "tool":
            lines.append(f"[tool result] ({len(content)} chars)")
    detail = "\n".join(lines)
    return _collapsible(
        f"<span style='color:#888;font-size:13px;'>{summary}</span>",
        detail,
    )


def _render_sub_calls(sub_calls: list[dict]) -> str:
    """Collapsible block showing per-function traces from a run_python call."""
    if not sub_calls:
        return ""
    lines = [_sub_call_summary(sc) for sc in sub_calls]
    return _collapsible(
        f"<span style='color:#689;font-size:12px;'>sub_calls ({len(sub_calls)})</span>",
        "\n".join(lines),
    )


def _render_message(m: dict, max_chars: int | None = None, trace_tool_calls: list[dict] | None = None) -> str:
    """Render a single message as HTML.

    trace_tool_calls: the trace's tool_calls list, used to find sub_calls for tool results.
    """
    role = m["role"]
    content = m.get("content") or ""
    tool_calls = m.get("tool_calls", [])

    if role == "system":
        formatted = _format_json(content)
        return _collapsible(
            "<span style='color:#888;'>[system]</span>"
            f" <span style='color:#888;font-size:12px;'>({len(content)} chars)</span>",
            formatted if max_chars is None else formatted[:max_chars],
        )
    elif role == "user":
        return f"<div style='margin:8px 0;'><b style='color:#36a;'>[user]</b> {escape(content)}</div>"
    elif role == "assistant":
        if tool_calls:
            parts = []
            for tc in tool_calls:
                fn = tc["function"]
                # Show code blocks for run_python, JSON args for others
                args_raw = fn["arguments"]
                try:
                    args_parsed = json.loads(args_raw)
                except (json.JSONDecodeError, TypeError):
                    args_parsed = {}

                if fn["name"] == "run_python" and "code" in args_parsed:
                    code_html = escape(args_parsed["code"])
                    parts.append(
                        f"<div style='margin:4px 0;'>"
                        f"<b style='color:#483;'>[assistant]</b> calls "
                        f"<code>{escape(fn['name'])}</code>"
                        f"<pre style='margin:2px 0 4px 16px;font-size:12px;"
                        f"background:#f6f6f6;padding:8px;border-radius:4px;'>{code_html}</pre>"
                        f"</div>"
                    )
                else:
                    args = _format_json(args_raw)
                    parts.append(
                        f"<div style='margin:4px 0;'>"
                        f"<b style='color:#483;'>[assistant]</b> calls "
                        f"<code>{escape(fn['name'])}</code>"
                        f"<pre style='margin:2px 0 4px 16px;font-size:12px;'>{escape(args)}</pre>"
                        f"</div>"
                    )
            return "\n".join(parts)
        else:
            return (
                f"<div style='margin:8px 0;'>"
                f"<b style='color:#483;'>[assistant]</b> ({len(content)} chars)"
                f"<div style='margin:4px 0 8px 16px;white-space:pre-wrap;'>{escape(content)}</div>"
                f"</div>"
            )
    elif role == "tool":
        summary = _tool_result_summary(content)
        formatted = _format_json(content)
        if max_chars is not None and len(formatted) > max_chars:
            formatted = formatted[:max_chars] + f"\n... ({len(formatted) - max_chars} more chars)"
        result_html = _collapsible(
            f"<span style='color:#986;'>[tool result]</span> {escape(summary)}",
            formatted,
        )
        # Find matching sub_calls from trace
        if trace_tool_calls:
            for tc in trace_tool_calls:
                if tc.get("result") == content and tc.get("sub_calls"):
                    result_html += _render_sub_calls(tc["sub_calls"])
                    break
        return result_html
    return ""


def show_trace(data: dict, max_chars: int | None = None) -> None:
    """Render the full trace as HTML in Jupyter."""
    inner = data.get("trace", data)
    tool_calls = inner.get("tool_calls", [])
    messages = inner.get("messages", [])
    turns = inner.get("turns", [])
    tools = inner.get("tools", [])

    parts = []

    # Header
    passed = data.get("passed", False)
    badge_color = "#4a4" if passed else "#c44"
    badge_text = "PASS" if passed else "FAIL"

    # Count sub_calls for display
    total_sub_calls = sum(len(tc.get("sub_calls", [])) for tc in tool_calls)
    sub_calls_info = f", {total_sub_calls} sub_calls" if total_sub_calls else ""

    parts.append(
        f"<div style='margin-bottom:12px;'>"
        f"<span style='background:{badge_color};color:white;padding:2px 8px;"
        f"border-radius:3px;font-size:12px;font-weight:bold;'>{badge_text}</span>"
        f"&nbsp;&nbsp;<b>{escape(data['question'])}</b>"
        f"&nbsp;&nbsp;<span style='color:#888;font-size:13px;'>"
        f"{len(tool_calls)} tool calls{sub_calls_info}, {len(turns)} turns</span>"
        f"</div>"
    )

    # Assertions
    if data.get("assertions"):
        parts.append(f"<div style='margin-bottom:8px;font-size:13px;'>{_render_assertions(data['assertions'])}</div>")

    # Per-turn telemetry
    if turns:
        telem_lines = []
        for i, t in enumerate(turns, 1):
            cost = f" | ${t['cost']:.4f}" if t.get("cost") else ""
            telem_lines.append(f"Turn {i}: {t['prompt_tokens']} in, {t['completion_tokens']} out, {t['latency_s']}s{cost}")
        parts.append(_collapsible(
            "<span style='color:#888;font-size:13px;'>telemetry</span>",
            "\n".join(telem_lines),
        ))

    # Error
    if inner.get("error"):
        parts.append(f"<div style='color:#c44;margin:8px 0;'>Error: {escape(inner['error'])}</div>")

    # Turns
    if messages:
        asst_indices = [i for i, m in enumerate(messages) if m["role"] == "assistant"]
        prev_end = 0

        for turn_num, asst_idx in enumerate(asst_indices, 1):
            parts.append(
                f"<div style='border-top:2px solid #ddd;margin-top:16px;padding-top:8px;'>"
                f"<span style='font-size:13px;color:#888;'>Turn {turn_num} — "
                f"model receives {asst_idx} messages"
                f"{f' + {len(tools)} tool defs' if tools else ''}"
                f"</span></div>"
            )

            if prev_end == 0:
                parts.append(_render_tools(tools))
                parts.append(_render_cached(messages[:prev_end]))
            else:
                parts.append(_render_cached(messages[:prev_end], tools=tools))

            # New input
            for i in range(prev_end, asst_idx):
                parts.append(_render_message(messages[i], max_chars, trace_tool_calls=tool_calls))

            # Response
            parts.append("<div style='border-left:3px solid #483;padding-left:12px;margin:8px 0;'>")
            parts.append(_render_message(messages[asst_idx], max_chars, trace_tool_calls=tool_calls))
            parts.append("</div>")

            prev_end = asst_idx + 1
    else:
        parts.append("<div style='color:#888;'>No messages — rerun collect_traces.py</div>")

    display(HTML("\n".join(parts)))


# Load and read a trace — change the workspace and slug
trace = load_trace(MODEL, "sherlock-holmes", "what-happens-in-a-scandal-in-bohemia")
show_trace(trace, max_chars=2000)

### Full API view — see exactly what the model received

For traces collected with the latest `collect_traces.py`, the full messages
array is stored in the trace JSON. For older traces, this field will be missing.

In [9]:
LOGS_PATH = Path("../logs/llm_calls.jsonl")


def load_api_calls() -> list[dict]:
    """Load all raw API calls from the JSONL log."""
    if not LOGS_PATH.exists():
        print(f"No log file at {LOGS_PATH}")
        return []
    with LOGS_PATH.open() as f:
        return [json.loads(line) for line in f]


def find_conversation(api_calls: list[dict], question: str) -> list[dict]:
    """Find the sequence of API calls for a given question.

    Looks for calls where the user message matches, then collects
    consecutive calls with growing message counts (same conversation).
    """
    matches = []
    for i, call in enumerate(api_calls):
        msgs = call.get("messages", [])
        user_msgs = [m for m in msgs if m["role"] == "user"]
        if user_msgs and question.lower() in user_msgs[-1].get("content", "").lower():
            matches.append(i)

    if not matches:
        print(f"No API calls found matching: {question[:60]}")
        return []

    # Take the last match (most recent run) and collect the full conversation
    start = matches[-1]
    conversation = [api_calls[start]]
    prev_msg_count = len(api_calls[start]["messages"])

    for i in range(start + 1, len(api_calls)):
        msg_count = len(api_calls[i]["messages"])
        if msg_count > prev_msg_count:
            conversation.append(api_calls[i])
            prev_msg_count = msg_count
        else:
            break

    return conversation


def show_api_turn(call: dict, turn: int, show_content: bool = True, max_chars: int | None = None) -> None:
    """Print one API call — what the model saw and what it responded."""
    msgs = call["messages"]
    prompt_tokens = call.get("prompt_tokens", "?")
    completion_tokens = call.get("completion_tokens", "?")

    def truncate(text: str) -> str:
        if max_chars is None or len(text) <= max_chars:
            return text
        return text[:max_chars] + f"\n  ... ({len(text) - max_chars} more chars)"

    print(f"{'=' * 80}")
    print(f"TURN {turn} | {len(msgs)} messages | prompt: {prompt_tokens} tokens | completion: {completion_tokens} tokens")
    print(f"{'=' * 80}")

    for m in msgs:
        role = m["role"]
        content = m.get("content") or ""
        tool_calls = m.get("tool_calls", [])

        if role == "system":
            print(f"\n[system] ({len(content)} chars)")
            if show_content:
                print(truncate(content))
        elif role == "user":
            print(f"\n[user] {content}")
        elif role == "assistant":
            if tool_calls:
                for tc in tool_calls:
                    fn = tc["function"]
                    print(f"\n[assistant] calls {fn['name']}({fn['arguments'][:200]})")
            elif content:
                print(f"\n[assistant] ({len(content)} chars)")
                if show_content:
                    print(truncate(content))
        elif role == "tool":
            print(f"\n[tool result] ({len(content)} chars)")
            if show_content:
                print(truncate(content))

    # Show what the model responded
    resp = call.get("response")
    if resp:
        print(f"\n--- RESPONSE ---")
        if resp.get("tool_calls"):
            for tc in resp["tool_calls"]:
                print(f"  calls {tc['name']}({tc['arguments'][:200]})")
        elif resp.get("content"):
            print(f"  {truncate(resp['content'])}")


api_calls = load_api_calls()
print(f"Loaded {len(api_calls)} API calls from {LOGS_PATH}")

Loaded 72 API calls from ../logs/llm_calls.jsonl

## 3. Note — open coding

After reading each trace, write a short note about what you observed.
After 20-30 traces, patterns will emerge. Add notes as rows below.

In [10]:
# Add a row each time you read a trace.
# After 20-30, look for clusters.
notes = pd.DataFrame([
    # {"model": MODEL, "workspace": "federalist-papers", "slug": "which-papers-discuss-the-judiciary", "note": "paginated read_file in chunks of 100 when whole file would fit"},
    # {"model": MODEL, "workspace": "world-factbook", "slug": "what-is-the-population-of-japan", "note": "answered from memory, 0 tool calls"},
    {"model": MODEL, "workspace": "federalist-papers", "slug": "which-papers-discuss-the-judiciary", "note": "model infers papers from file names without reading them. it just verified a few by reading the first 20 lines. Then it became confident enough to answer from its priors."}
], columns=["model", "workspace", "slug", "note"])
notes

,model,workspace,slug,note
0,openrouter-qwen-qwen3-coder,federalist-papers,which-papers-discuss-the-judiciary,model infers papers from file names without reading them...

## 4. Cluster — group notes into failure categories

Once you have enough notes, group them. Common categories:
- **skipped tools** — answered from memory
- **over-searching** — hit max_turns without concluding
- **pagination waste** — read_file in small chunks instead of whole file
- **wrong grounding** — found evidence but overrode it with training data
- **missed variant** — searched one term, didn't try synonyms

In [11]:
# Once you've filled in notes above, count them by pattern
if len(notes) > 0:
    notes["note"].value_counts()
else:
    print("No notes yet — start reading traces!")

## 5. Compare — tool call patterns across traces

In [ ]:
def trace_summary(model_slug: str) -> pd.DataFrame:
    """Load all traces for a model and summarize tool usage."""
    rows = []
    model_dir = TRACES_DIR / model_slug
    for ws_dir in sorted(model_dir.iterdir()):
        if not ws_dir.is_dir():
            continue
        for trace_file in sorted(ws_dir.glob("*.json")):
            data = json.loads(trace_file.read_text())
            inner = data.get("trace", data)
            tcs = inner.get("tool_calls", [])
            # Count sub_calls across all tool calls
            all_sub_calls = []
            for tc in tcs:
                all_sub_calls.extend(tc.get("sub_calls", []))
            sub_call_names = [sc["name"] for sc in all_sub_calls]
            # Build sequence from sub_calls if available, else from tool_calls
            if sub_call_names:
                abbreviations = {"list_files": "L", "search_files": "S", "read_file": "R"}
                sequence = "→".join(abbreviations.get(n, "?") for n in sub_call_names)
            else:
                tool_names = [tc["name"] for tc in tcs]
                abbreviations = {"list_files": "L", "search_files": "S", "read_file": "R",
                                 "run_python": "P", "calculator": "C", "get_current_time": "T"}
                sequence = "→".join(abbreviations.get(t, "?") for t in tool_names)
            rows.append({
                "workspace": ws_dir.name,
                "question": data["question"][:50],
                "passed": data["passed"],
                "tool_calls": len(tcs),
                "sub_calls": len(all_sub_calls),
                "sequence": sequence,
                "searches": sub_call_names.count("search_files"),
                "reads": sub_call_names.count("read_file"),
                "lists": sub_call_names.count("list_files"),
            })
    return pd.DataFrame(rows)

trace_summary(MODEL)

In [13]:
# Tool calls CSV — if available (requires a collect_traces run with the latest schema)
tool_calls_csv = TRACES_DIR / "tool_calls.csv"
if tool_calls_csv.exists():
    tc_df = pd.read_csv(tool_calls_csv)
    print(f"{len(tc_df)} tool calls across {tc_df['trace_id'].nunique()} traces")

    # Error rate by tool
    tc_df["has_error"] = tc_df["error"].notna() & (tc_df["error"] != "")
    tc_df.groupby("tool")["has_error"].agg(["sum", "count", "mean"]).rename(
        columns={"sum": "errors", "count": "total", "mean": "error_rate"}
    ).sort_values("error_rate", ascending=False)
else:
    print("No tool_calls.csv yet — run: uv run python scripts/collect_traces.py")

180 tool calls across 13 traces